language: generic
sudo: true
cache:
  directories:
    - test/dot_emacs_25
    - test/dot_emacs_26
    - test/dot_emacs_master
services:
  - docker
env:
  matrix:
    - EMACS_VERSION=emacs25
    - EMACS_VERSION=emacs26
    - EMACS_VERSION=master
before_install:
  - docker-compose build $EMACS_VERSION
install:
  - docker-compose run --rm  $EMACS_VERSION emacs --batch -l ./test/setup.el -eval '(message "Setup finished")'
script:
  - docker-compose run --rm $EMACS_VERSION ./test/test_all
